spring.application.name=webcrawler
seed-url=https://monzo.com
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
max-depth=5
crawler.parse-strategy=selenium
pool-size=10