/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * mainJFrame.java
 *
 */

package com.ankur.webcurve.ui;

import com.ankur.webcurve.client.MarketDepth;
import com.ankur.webcurve.client.MarketTrade;
import com.ankur.webcurve.common.ExchangeEventListener;
import com.ankur.webcurve.common.Order;
import com.ankur.webcurve.fix.ExchangeFixAgent;
import lombok.extern.slf4j.Slf4j;

import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.awt.*;
import java.util.*;

/**
 * @author dennis_dun_chen@yahoo.com
 */
@Slf4j
public class MarketDepthJFrame extends JFrame {
    // user code

	ExchangeFixAgent fixAgent = new ExchangeFixAgent();
	private MarketDepth marketDepth;
	private ArrayList<MarketTrade> marketTrades;
	Map<String, MarketDepth> marketDepthMap = Collections.synchronizedMap(new HashMap<String, MarketDepth>());
	Map<String, ArrayList<MarketTrade>> marketTradeMap = Collections.synchronizedMap(new HashMap<String, ArrayList<MarketTrade>>());
    private String cfgFile;
    
    /** Creates new form mainJFrame */
    public MarketDepthJFrame(String cfgFile) {
    	this.fixAgent = fixAgent;
    	this.cfgFile = cfgFile;
        initComponents();
        myInitComponents();
        updateBookView();
    }


    private void myInitComponents()
    {

        // set frame size and location
    	this.setTitle("Webcurve Simulator - Copyright (c) 2001-2005 to Dennis_d_Chen@yahoo.com");
        setSize(700, 500);
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        setLocation((dim.width-700)/2, (dim.height-500)/2);
        fixAgent.Open(cfgFile);
        if(!cbStock.getSelectedItem().toString().equals(""))
            setBook(cbStock.getSelectedItem().toString());

        updateBookView();
    }


    public void setBook(String code)
    {
    
    	marketDepth = marketDepthMap.get(code);
    	if (null == marketDepth)
    	{
    		marketDepth = new MarketDepth();
    		marketDepth.setSymbol(code);
    		marketDepthMap.put(code, marketDepth);
    		fixAgent.subscribeMarketData(code, marketDepthListener, marketTradeListener);
    	}
    	
    	marketTrades = marketTradeMap.get(code);
     }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new JTabbedPane();
        jPanel1 = new JPanel();
        jPanel4 = new JPanel();
        jSplitPane2 = new JSplitPane();
        jSplitPane1 = new JSplitPane();
        jScrollPane1 = new JScrollPane();
        lstBid = new JTable();
        jScrollPane2 = new JScrollPane();
        lstAsk = new JTable();
        jScrollPane3 = new JScrollPane();
        lstTrade = new JTable();
        jPanel3 = new JPanel();
        jLabel3 = new JLabel();
        lbExchange = new JLabel();
        jLabel2 = new JLabel();
        lbVWAP = new JLabel();
        cbStock = new JComboBox();
        cbExchange = new JComboBox();
        tbInstance = new JTextField();
        btBook = new JButton();
        jMenuBar1 = new JMenuBar();
        jMenu1 = new JMenu();
        jMenu2 = new JMenu();

        setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);
        setName("frMain"); // NOI18N
        getContentPane().setLayout(new java.awt.CardLayout());

        jPanel1.setLayout(new java.awt.BorderLayout());

        jPanel4.setLayout(new java.awt.BorderLayout());

        jSplitPane2.setDividerLocation(500);

        jSplitPane1.setDividerLocation(250);

        lstBid.setModel(new DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Broker", "Volume", "Price"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(lstBid);

        jSplitPane1.setLeftComponent(jScrollPane1);

        lstAsk.setModel(new DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Price", "Volume", "Broker"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(lstAsk);

        jSplitPane1.setRightComponent(jScrollPane2);

        jSplitPane2.setLeftComponent(jSplitPane1);

        lstTrade.setModel(new DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Trade Price", "Volume"
            }
        ));
        jScrollPane3.setViewportView(lstTrade);

        jSplitPane2.setRightComponent(jScrollPane3);

        jPanel4.add(jSplitPane2, java.awt.BorderLayout.CENTER);

        jPanel1.add(jPanel4, java.awt.BorderLayout.CENTER);

        jPanel3.setLayout(new java.awt.GridLayout(2, 0));

        jLabel3.setText("Stock:");
        jPanel3.add(jLabel3);

        lbExchange.setText("Exchange:");
        jPanel3.add(lbExchange);

        jLabel2.setText("Instance:");
        jPanel3.add(jLabel2);

        lbVWAP.setHorizontalAlignment(SwingConstants.LEFT);
        lbVWAP.setText("VWAP:");
        jPanel3.add(lbVWAP);

        cbStock.setEditable(true);
        cbStock.setModel(new DefaultComboBoxModel(new String[] { "0005.HK", "0011.HK", "0857.HK", "3968.HK", "1398.HK", "BHP.AX", "CBA.AX", "ANZ.AX", "WOW.AX" }));
        cbStock.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbStockActionPerformed(evt);
            }
        });
        jPanel3.add(cbStock);

        cbExchange.setModel(new DefaultComboBoxModel(new String[] { "HKEX", "ASX", "TWSE", "KRX", "SGX", "JSX" }));
        cbExchange.addHierarchyBoundsListener(new java.awt.event.HierarchyBoundsListener() {
            public void ancestorMoved(java.awt.event.HierarchyEvent evt) {
                cbExchangeAncestorMoved(evt);
            }
            public void ancestorResized(java.awt.event.HierarchyEvent evt) {
            }
        });
        jPanel3.add(cbExchange);

        tbInstance.setText("0");
        jPanel3.add(tbInstance);

        btBook.setText("Detail");
        jPanel3.add(btBook);

        jPanel1.add(jPanel3, java.awt.BorderLayout.PAGE_START);

        jTabbedPane1.addTab("Order Book", jPanel1);

        getContentPane().add(jTabbedPane1, "card2");
        jTabbedPane1.getAccessibleContext().setAccessibleName("orderBookTab");

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Command");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void enterOrder(Order.SIDE side)
    {

    }

    private void cbExchangeAncestorMoved(java.awt.event.HierarchyEvent evt) {//GEN-FIRST:event_cbExchangeAncestorMoved
        // TODO add your handling code here:
}//GEN-LAST:event_cbExchangeAncestorMoved

    private void updateBookView()
    {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
            	if (marketDepth == null)
            		return;
            	ArrayList<Double> bids = marketDepth.getBids();
            	ArrayList<Long> bidVols = marketDepth.getBidVols();
		        //lstBid.removeAll();
		        DefaultTableModel model = (DefaultTableModel)lstBid.getModel();
		        model.setRowCount(0);
		        for (int i=0; i<bids.size(); i++)
		        {
		            Double price = bids.get(i);
		            Long qty = bidVols.get(i);
		            model.addRow( new Object[]{"",
		                                       qty,
		                                       price
		                });
		        }
		
            	ArrayList<Double> asks = marketDepth.getAsks();
            	ArrayList<Long> askVols = marketDepth.getAskVols();
		        
		        model = (DefaultTableModel)lstAsk.getModel();
		        model.setRowCount(0);
		        for (int i=0; i<asks.size(); i++)
		        {
		            Double price = asks.get(i);
		            Long qty = askVols.get(i);
		            model.addRow( new Object[]{price,
		                                       qty,
		                                       ""
		                });
		        }
		
		        model = (DefaultTableModel)lstTrade.getModel();
		        model.setRowCount(0);
		        if (marketTrades == null)
		        	return;
		        for (int i=0; i<marketTrades.size(); i++)
		        {
		            model.addRow( new Object[]{marketTrades.get(i).getPrice(), marketTrades.get(i).getVol()});
		        }
		
		        //VWAP
		        //lbVWAP.setText("VWAP: " + new DecimalFormat("###,###.###").format(currentBook.getVWAP().doubleValue()));
            }
        });
    }

    private void cbStockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbStockActionPerformed
        // TODO add your handling code here:
        setBook(cbStock.getSelectedItem().toString());
        updateBookView();
    }//GEN-LAST:event_cbStockActionPerformed

    private void cancelOrders(JTable table, Vector<Order> orders)
    {
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private JButton btBook;
    private JComboBox cbExchange;
    private JComboBox cbStock;
    private JLabel jLabel2;
    private JLabel jLabel3;
    private JMenu jMenu1;
    private JMenu jMenu2;
    private JMenuBar jMenuBar1;
    private JPanel jPanel1;
    private JPanel jPanel3;
    private JPanel jPanel4;
    private JScrollPane jScrollPane1;
    private JScrollPane jScrollPane2;
    private JScrollPane jScrollPane3;
    private JSplitPane jSplitPane1;
    private JSplitPane jSplitPane2;
    private JTabbedPane jTabbedPane1;
    private JLabel lbExchange;
    private JLabel lbVWAP;
    private JTable lstAsk;
    private JTable lstBid;
    private JTable lstTrade;
    private JTextField tbInstance;
    // End of variables declaration//GEN-END:variables


    ExchangeEventListener<MarketDepth> marketDepthListener = new ExchangeEventListener<MarketDepth>()
    {

		@Override
		public void onChangeEvent(MarketDepth t) {
			log.info("received MarketDepth: ");
			t.print();
			marketDepthMap.put(t.getSymbol(), t);
			if (marketDepth != null && t.getSymbol().equals(marketDepth.getSymbol()))
			{
				log.info("setting current MarketDepth: ");
				marketDepth = t;
				updateBookView();
			}
				
		}
    	
    };
    
    ExchangeEventListener<MarketTrade> marketTradeListener = new ExchangeEventListener<MarketTrade>()
    {

		@Override
		public void onChangeEvent(MarketTrade t) {
			log.info("received MarketTrade: " + t.getSymbol() + " " + t.getVol() + "@" + t.getPrice());
			
			ArrayList<MarketTrade> marketTrades = marketTradeMap.get(t.getSymbol());
			if (null == marketTrades)
			{
				marketTrades = new ArrayList<MarketTrade>();
				marketTradeMap.put(t.getSymbol(), marketTrades);
			}
			marketTrades.add(t);
			if (marketDepth != null && t.getSymbol().equals(marketDepth.getSymbol()))
			{
		
				MarketDepthJFrame.this.marketTrades = marketTrades;
				updateBookView();
			}
			
			
		}
    	
    };

	public static void main(String[] args) {
	    String cfgFile = "";
        if (args.length>0)
        	cfgFile = args[0];

    	class RunIt implements Runnable {
    		private String cfgFile;
    		public RunIt (String cfgFile) 
    		{
    			this.cfgFile = cfgFile;
    		}
            public void run() {
                new MarketDepthJFrame(cfgFile).setVisible(true);
            }
        };
        java.awt.EventQueue.invokeLater(new RunIt(cfgFile));

	}

}
