services:
  postgres:
    image: postgres:16-alpine
    container_name: outbox-postgres
    environment:
      POSTGRES_DB: outboxdb
      POSTGRES_USER: outboxuser
      POSTGRES_PASSWORD: outboxpass
    ports:
      - "5434:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./src/main/resources/schema.sql:/docker-entrypoint-initdb.d/schema.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U outboxuser -d outboxdb"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: