spring.application.name=market-feed

# Market Feed Configuration
market.feed.min.instruments=5
market.feed.max.instruments=10
market.feed.avg.millis.between.quotes=100

# Server Configuration
server.port=9090

# Logging
logging.level.com.ankur.exchange.feed=INFO
