spring.application.name=candlesticks
server.port=9000
partner.enabled=true
partner.instruments-uri=ws://localhost:9090/instruments
partner.quotes-uri=ws://localhost:9090/quotes

spring.datasource.url=jdbc:postgresql://localhost:5432/ankurbrdwj
spring.datasource.username=postgres
spring.datasource.password=postgres123
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=create

# (Optional) Enable SQL logging to verify DDL statements executed at startup
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false

logging.level.com.ankur.candlesticks=info

spring.security.user.name=admin
spring.security.user.password=admin123

management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=always
