services:
  app:
    build: .
    container_name: price-alert-app
    depends_on:
      - postgres
    ports:
      - "9095:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/price_alerts
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres123
      SPRING_KAFKA_BOOTSTRAP_SERVERS: host.docker.internal:9092
      MARKET_FEED_WEBSOCKET_URL: ws://host.docker.internal:9090/quotes
    restart: on-failure

  postgres:
    image: postgres:15-alpine
    container_name: price-alert-postgres
    environment:
      POSTGRES_DB: price_alerts
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres123
    ports:
      - "5435:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./postgres-init:/docker-entrypoint-initdb.d
    restart: always

  conduktor-console:
    image: conduktor/conduktor-console:latest
    container_name: price-alert-conduktor
    depends_on:
      - postgres
    ports:
      - "9080:8080"
    environment:
      CDK_DATABASE_URL: postgresql://postgres:postgres123@postgres:5432/conduktor
      CDK_ADMIN_EMAIL: admin@admin.io
      CDK_ADMIN_PASSWORD: Admin123!
      CDK_CLUSTERS_0_ID: local
      CDK_CLUSTERS_0_NAME: Local Kafka
      CDK_CLUSTERS_0_BOOTSTRAPSERVERS: host.docker.internal:9092
      CDK_CLUSTERS_0_SECURITY_PROTOCOL: PLAINTEXT
    restart: always

volumes:
  postgres_data: