plugins {
  id 'java'
  id 'org.springframework.boot' version '3.4.2'
  id 'io.spring.dependency-management' version '1.1.7'
  id 'io.freefair.lombok'  version "8.12"
}

allprojects {
  repositories {
    mavenCentral()
    maven {
      url "https://repo.spring.io/milestone"
    }
  }
  group = 'com.ankur.daily.meals'
  version = '1.0.0'
}

subprojects {
  apply plugin: 'java'
  apply plugin: 'io.spring.dependency-management'

  group = 'com.ankur.daily.meals'
  version = '1.0.0'

  java {
    sourceCompatibility = JavaVersion.VERSION_17
    targetCompatibility = JavaVersion.VERSION_17
  }

  buildscript {
    repositories {
      mavenCentral()
      maven {
        url "https://repo.spring.io/milestone"
      }
    }
    dependencies {
      classpath "org.springframework.boot:spring-boot-gradle-plugin:2.6.0"
      classpath "org.springframework.boot:spring-boot-starter-data-neo4j:2.6.0"
      classpath "org.springframework.boot:spring-boot-starter-data-rest:2.6.0"
      classpath "org.springframework.boot:spring-boot-starter-hateoas:2.6.0"
      classpath "org.springframework.boot:spring-boot-starter-web:2.6.0"
      classpath "org.springframework.ai:spring-ai-neo4j-store:1.0.0-M5"
      classpath "org.projectlombok:lombok:1.18.22"
      classpath "org.springframework.boot:spring-boot-starter-test:2.6.0"
      classpath "org.junit.platform:junit-platform-launcher:1.8.2"
    }
  }

}
