spring.application.name=spring-postgres
server.port=6080
spring.datasource.url=jdbc:postgresql://localhost:5442/practice
spring.datasource.username=postgres
spring.datasource.password=password
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
